title: Anthony Bald
email: abald@g.harvard.edu
description: ... find me on social media!

twitter_username: AnthonyPBald
github_username: anthonybald
linkedin_username: anthonybald

theme: minima
minima:
  date_format: "%b %-d, %Y"

header_pages:
  - index.md
  - about-me.md
  - research.md
  - resources.md