# Setup
title: Anthony Bald
image: images/ripl-ab.png
description: PhD Candidate in Public Policy
email: abald@g.harvard.edu
url: https://anthonybald.com/
cv: cv/bald-cv-july-2021.pdf

# Posts
baseurl: /
paginate: 5
author:
  name: Anthony Bald
  url: https://anthonybald.com/
  email: abald@g.harvard.edu

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Custom vars
version: 2.1.0
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
