theme: jekyll-theme-minimal

title: Anthony Bald
logo: /assets/img/RIPL_AB.png
description: Welcome to my website
cv: /cv/bald_cv_may2019.pdf
twitter: https://www.twitter.com/AnthonyPBald
linkedin: https://www.linkedin.com/in/anthonybald
